databases:
  - name: driver-transport-db
    regions: singapore(southeast asia)
    type: postgresql

services:
  - type: web
    name: my-fastapi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn driver_app.main:app --host 0.0.0.0 --port ${PORT:-8000}
    plan: free
    autoDeploy: true
    envVars:
      DATABASE_URL: ${DATABASE_URL}  # Render will set this automatically
