"""add new column to drivesr table and expenses table

Revision ID: 6236fcb6204d
Revises: bb3760f7329d
Create Date: 2024-08-09 10:17:24.924473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6236fcb6204d'
down_revision: Union[str, None] = 'bb3760f7329d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('driver_name', sa.String(), nullable=True))
    op.add_column('trips', sa.Column('driver_name', sa.String(), nullable=True))
    op.drop_index('ix_trips_customer_name', table_name='trips')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_trips_customer_name', 'trips', ['customer_name'], unique=False)
    op.drop_column('trips', 'driver_name')
    op.drop_column('expenses', 'driver_name')
    # ### end Alembic commands ###
