"""add new column user_type to users table

Revision ID: e9b180ded6f2
Revises: 6236fcb6204d
Create Date: 2024-08-10 11:40:15.633148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b180ded6f2'
down_revision: Union[str, None] = '6236fcb6204d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ### op.add_column('users', sa.Column('user_type', sa.String(length=20), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
